use R's CC for compilation
git-svn-id: https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/zlibbioc@55922 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1633,7 +1633,16 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-cd src/zlib-1.2.5 && ./configure --zprefix && cd ../..
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+R_CC=`"${R_HOME}/bin/R" CMD config CC`
+
+cd src/zlib-1.2.5 && \
+  CC=${R_CC} ./configure --zprefix && \
+  cd ../..
 
 ac_config_files="$ac_config_files src/Makevars"
 
