only build libzbioc on non-Windows when explicitly asked
- configure argument --with-libzbioc default [no]
- src/Makefile.in uses $(MAKE) and non-GNU idiom -C


git-svn-id: https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/zlibbioc@58558 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -556,6 +556,7 @@ PACKAGE_URL=
 ac_unique_file=""DESCRIPTION""
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
+LIBZBIOC
 target_alias
 host_alias
 build_alias
@@ -597,6 +598,7 @@ SHELL'
 ac_subst_files=''
 ac_user_opts='
 enable_option_checking
+with_libzbioc
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1205,6 +1207,11 @@ if test -n "$ac_init_help"; then
 
   cat <<\_ACEOF
 
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-libzbioc         build and use libzbioc [no]
+
 Report bugs to the package provider.
 _ACEOF
 ac_status=$?
@@ -1633,16 +1640,30 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-: ${R_HOME=`R RHOME`}
-if test -z "${R_HOME}"; then
-  echo "could not determine R_HOME"
-  exit 1
+
+# Check whether --with-libzbioc was given.
+if test "${with_libzbioc+set}" = set; then :
+  withval=$with_libzbioc; use_libzbioc=$withval
+else
+  use_libzbioc=no
 fi
-R_CC=`"${R_HOME}/bin/R" CMD config CC`
-R_CFLAGS=`"${R_HOME}/bin/R" CMD config CPICFLAGS`
-cd src/zlib-1.2.5 && \
-  CC=${R_CC} CFLAGS=${R_CFLAGS} ./configure --zprefix && \
-  cd ../..
+
+
+if test "${use_libzbioc}" = yes; then
+  : ${R_HOME=`R RHOME`}
+  if test -z "${R_HOME}"; then
+    echo "could not determine R_HOME"
+    exit 1
+  fi
+  R_CC=`"${R_HOME}/bin/R" CMD config CC`
+  R_CFLAGS=`"${R_HOME}/bin/R" CMD config CPICFLAGS`
+
+  cd src/zlib-1.2.5 && \
+    CC=${R_CC} CFLAGS=${R_CFLAGS} ./configure --zprefix && \
+    cd ../..
+fi
+
+LIBZBIOC=${use_libzbioc}
 
 ac_config_files="$ac_config_files src/Makevars"
 
